Add check_certificate script
privacyidea/scripts pull request #10
Opened 2024-05-21 11:51 UTC by pablo-knight

### Documentation of the Certificate Check Script

#### Overview

This script is used to check TLS certificates for web servers and LDAP servers, as well as CA certificates. It allows you to check the validity of certificates and issue warnings if a certificate is about to expire. The script can optionally create log files.

#### Usage

The script is executed from the command line and supports several arguments to configure the certificate checks.

##### Command Line Arguments

- `--days`: (required) Number of days before expiration to issue a warning.
- `--config-dir`: Directory to search for web server configuration files.
- `--web`: Checks the web server certificate.
- `--ldap`: Checks the LDAP server certificate.
- `--ca`: Checks the CA certificate.
- `--all`: Checks all web server, LDAP server, and CA certificates.
- `--logging`: Path to the log file. If not set, logs will be printed to stdout.

##### Example Invocations

1. **Check all certificates and log to a file**

   ```bash
   python check_certificates.py --days 30 --all --logging /path/to/logfile.log
   ```

2. **Check only web server certificates and output to console**

   ```bash
   python check_certificates.py --days 30 --web
   ```

3. **Check LDAP server certificates and log to a file**

   ```bash
   python check_certificates.py --days 30 --ldap --logging /path/to/logfile.log
   ```

4. **Check CA certificates and output to console**

   ```bash
   python check_certificates.py --days 30 --ca
   ```

#### Sample Output

When the script runs, the output may look like this:

```plaintext
2024-05-17 13:39:15,315 - INFO - CA issuer from resolver "ad" certificate is valid for 619 more days.
2024-05-17 13:39:15,316 - INFO - CA issuer from resolver "ucs07" certificate is valid for 1373 more days.
2024-05-17 13:39:15,316 - INFO - CA issuer from resolver "ucs05" certificate is valid for 883 more days.
```

#### Error Handling

The script handles various types of errors, such as failing to retrieve certificates or problems reading configuration files, and outputs corresponding error messages:

```plaintext
Failed to retrieve certificate from 10.10.10.121: Command 'echo | openssl s_client -connect 10.10.10.121:389 -starttls ldap 2>/dev/null | openssl x509' returned non-zero exit status 1.
Failed to connect to 10.10.1.121:389: Command 'echo | openssl s_client -connect 10.10.10.121:389 2>/dev/null' returned non-zero exit status 1.
```

#### Summary

This script is a helpful tool for administrators to monitor the validity of TLS certificates in their systems and receive timely warnings when certificates need to be renewed. By supporting log files and various operating modes, it can be flexibly integrated into different monitoring and maintenance processes.

2024-05-21 11:51 UTC, pep8speaks commented
Hello @pablo-knight! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`toolbox/check_certificates.py`](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py):

> [Line 3:82](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L3): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 4:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L4): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 4:81](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L4): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L5): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 17:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L17): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 28:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L28): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 42:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L42): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 54:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L54): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 71:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L71): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 83:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L83): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 88:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L88): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 91:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L91): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 100 characters)
> [Line 94:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L94): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 106:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (155 > 100 characters)
> [Line 108:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L108): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 118:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 100 characters)
> [Line 120:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L120): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 100 characters)
> [Line 126:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L126): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 100 characters)
> [Line 131:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L131): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 100 characters)
> [Line 134:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L134): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 100 characters)
> [Line 140:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L140): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 153:9](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L153): [E133](https://duckduckgo.com/?q=pep8%20E133) closing bracket is missing indentation
> [Line 156:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L156): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 100 characters)
> [Line 158:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L158): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 162:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L162): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 100 characters)
> [Line 163:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L163): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 100 characters)
> [Line 164:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L164): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 100 characters)
> [Line 168:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)
> [Line 169:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L169): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (120 > 100 characters)
> [Line 176:5](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L176): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 186:9](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L186): [E133](https://duckduckgo.com/?q=pep8%20E133) closing bracket is missing indentation
> [Line 189:1](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L189): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 212:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L212): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 100 characters)
> [Line 216:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L216): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 100 characters)
> [Line 218:101](https://github.com/privacyidea/scripts/blob/5571ce7928cbeb7cd3e1d44307a20af84f759bc4/toolbox/check_certificates.py#L218): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (155 > 100 characters)
> [Line 219:1](https://github.com/privacyidea/scripts/blob/5571ce792 [...]

2024-06-10 14:25 UTC, plettich requested changes

2024-06-10 14:25 UTC, plettich commented on toolbox/check_certificates.py
> +        '--days', type=int, required=True, help='No. of days before expiration to issue a warning.')
if the argument `days` is required it should be an argument.
Otherwise we can just add a default value like "30" and the script won't nag about the missing parameter.

2024-06-10 14:25 UTC, plettich commented on toolbox/check_certificates.py
> +        '--ca', action='store_true', help='Check the CA issuer certificate.')
Please remove the `--ca` argument. When it is configured in the LDAP-Resolver, we check it anyway.

2024-06-10 14:25 UTC, plettich commented on toolbox/check_certificates.py
> +            "nginx": "/etc/nginx/sites-enabled"}
Please check if nginx uses the same name for the SSL Certificate file in the configuration like  apache (`SSLCertificateFile`)

2024-06-10 14:25 UTC, plettich commented on toolbox/check_certificates.py
> +    if ca_checks:
remove this block, it is redundant since the CA will be checked as well when `--ldap` or `--all` is given.

2024-06-10 14:25 UTC, plettich commented on toolbox/check_certificates.py
> +        log_message(f"Error reading {config_path}: {str(e)}", error=True)
You don't need to convert everything with `str()`, the f-string functionality does that automatically.

2024-06-11 00:06 UTC, plettich requested changes

2024-06-11 00:06 UTC, plettich commented on toolbox/check_certificates.py
> +    :param log_path: The path to the log file.
please add a newline between the documentation and the parameter description. Should we create a documentation from this it would be rendered incorrectly.

2024-06-11 00:06 UTC, plettich commented on toolbox/check_certificates.py
> +                   f"2>/dev/null | openssl x509")
we could use `ssl.get_server_certificate()` here (https://docs.python.org/3.8/library/ssl.html?highlight=starttls#ssl.get_server_certificate).
This avoids the external call and we can set the TLS version.

2024-06-11 10:46 UTC, pablo-knight commented on toolbox/check_certificates.py
> +            "nginx": "/etc/nginx/sites-enabled"}
should also work for nginx

2024-06-11 13:39 UTC, plettich requested changes

2024-06-11 13:39 UTC, plettich commented on toolbox/check_certificates.py
> +__doc__ = """
Please remove the `__doc__` part. It is not necessary. The docstring will be available via the `.__doc__` attribute of the module.

2024-06-11 13:39 UTC, plettich commented on toolbox/check_certificates.py
> +- `--days`: If not set, it will use 30 days as default.
the second `--days:` is not necessary. Just indent the second line.

2024-06-11 13:39 UTC, plettich commented on toolbox/check_certificates.py
> +- `--all`: Checks all web server, LDAP server, and CA certificates.
Maybe we should make `--all` the default (check all configured certificates). Only if `--web` or `--ldap` is given, check this specific configuration.
Also: if `--ldap` is given, the certificates of all resolvers will be checked. We could make this optionally based on the resolver name. But we can do that later as well.

2024-06-11 13:39 UTC, plettich commented on toolbox/check_certificates.py
> +                   f"2>/dev/null | openssl x509")
We could use a `socket` to get the `STARTTLS` certificate: https://stackoverflow.com/a/5655076
But we should do that later as well.

2024-06-12 12:26 UTC, plettich requested changes

2024-06-12 12:26 UTC, plettich commented on toolbox/check_certificates.py
> +        days_to_expire = (cert.not_valid_after - datetime.now()).days
Just ran into this, `not_valid_after` is deprecated in favor of `not_valid_after_utc`. You need to compare this with
`datetime.datetime.now(tz=datetime.timezone.utc)`.

2024-06-12 12:26 UTC, plettich commented on toolbox/check_certificates.py
> +
Maybe also add an example for a non-default configuration location like:
```
PRIVACYIDEA_CONFIGFILE=/path/to/pi.cfg check_certificates.py
```

2024-06-12 12:30 UTC, plettich requested changes

2024-06-12 12:30 UTC, plettich commented on toolbox/check_certificates.py
> +if __name__ == "__main__":
and please fix the pep8 issues.

2024-06-12 13:21 UTC, plettich commented on toolbox/check_certificates.py
> +        days_to_expire = (cert.not_valid_after - datetime.now()).days
You can use something like this:
```python
        try:
            days_to_expire = (cert.not_valid_after_utc - datetime.datetime.now(tz=datetime.timezone.utc)).days
        except AttributeError as _e:
            # looks like pyca/cryptography version < 42.0
            days_to_expire = (cert.not_valid_after - datetime.datetime.utcnow()).days
```

2024-06-17 09:28 UTC, merged